version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  data_loader:
    image: python:3
    container_name: data_loader
    volumes:
      - .:/app
    depends_on:
      - mysql
    command: >
      sh -c "sleep 5 && pip3 install -r /app/requirements.txt && python3 /app/load.py"
